sudo: false
addons:
  apt:
    packages:
    - automake
    - colorgcc
    - debootstrap
    - libjemalloc1
    - libtool
    - lsb-release
    - openjdk-7-jdk
language: c
before_script:
  - lsb_release -a
  - $TRAVIS_CC --version
script:
  - ./autogen.sh
  - ./configure CC=$TRAVIS_CC
  - make
  - make test
env:
  global:
    - TEST_DEBOOTSTRAP=1
    - TEST_DEBOOTSTRAP_CACHE=cache
  matrix:
    - TRAVIS_CC=colorgcc EXTRA_CFLAGS='-Wall -Werror'
    - TRAVIS_CC=clang EXTRA_CFLAGS='-Wall -Werror'
    - TRAVIS_CC=clang EXTRA_CFLAGS='-std=c11 -Wall -Werror'
cache:
  directories:
    - test/cache
