dist: bionic

language: c

os:
  - linux

addons:
  apt:
    packages:
      - automake
      - colorgcc
      - debootstrap
      - fakeroot
      - libjemalloc1
      - libtool
      - lsb-release
      - openjdk-8-jdk-headless
      - openjdk-11-jdk-headless

before_script:
  - lsb_release -a
  - $TRAVIS_CC --version

script:
  - ./autogen.sh
  - ./configure CC=$TRAVIS_CC
  - make V=1
  - make test

env:

  global:
    - TEST_DEBOOTSTRAP=1
    - TEST_DEBOOTSTRAP_CACHE=cache

  matrix:
    - TRAVIS_CC=colorgcc EXTRA_CFLAGS='-Wall -Werror'
    - TRAVIS_CC=clang EXTRA_CFLAGS='-Wall -Werror'
    - TRAVIS_CC=clang EXTRA_CFLAGS='-std=c11 -Wall -Werror'

cache:
  directories:
    - test/cache
