language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq automake debootstrap libtool lsb-release
script: ./autogen.sh && ./configure && make && make test
env:
  - TEST_DEBOOTSTRAP=1
  - CFLAGS='-std=c11 -g -O2 -Wall -Wno-deprecated-declarations'
branches:
  except:
    - /^archive\//
    - /^stash\//
