language: c
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq automake debootstrap libtool lsb-release
script: ./autogen.sh && ./configure CC=$TRAVIS_CC && make && make test
env:
  global:
    - TEST_DEBOOTSTRAP=1
  matrix:
    - TRAVIS_CC=gcc
    - TRAVIS_CC=clang CFLAGS='-std=c11 -g -O2 -Wall -Wno-deprecated-declarations'
branches:
  except:
    - /^archive\//
    - /^stash\//
